Header header
float64 remove_points_farto
float64 remove_points_closeto
float64 clip_min_height
float64 clip_max_height

float64 ground_search_radius
float64 in_floor_max_height
float64 in_floor_max_angle

int32 cluster_size_min
int32 cluster_size_max
float64 clustering_distance

bool use_multiple_thres
float64[] clustering_ranges
int32[] cluster_sizes_min
int32[] cluster_sizes_max
float64[] clustering_distances

float64 cluster_merge_threshold
bool pose_estimation
bool remove_ground
